# Generated by Django 5.0.4 on 2024-04-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerAndaccessories', '0003_powertabletproduct_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerwarranty',
            name='duration',
        ),
    ]
