# Generated by Django 5.0.4 on 2024-04-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverAndglass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoverAndGlassProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock ', 'Out Of Stock ')], max_length=40)),
                ('image', models.ImageField(upload_to='coverAndglass/media/image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='coverAndglass.coverandglasscategroy')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='coverAndglass.color')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='coverAndglass.productmodel')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='coverAndglass.productsize')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='coverAndglass.warranty')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
