# Generated by Django 5.0.4 on 2024-04-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverAndglass', '0002_color_productmodel_productsize_warranty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverandglassproduct',
            name='color',
        ),
        migrations.AddField(
            model_name='coverandglassproduct',
            name='color',
            field=models.ManyToManyField(related_name='products', to='coverAndglass.color'),
        ),
    ]
