# Generated by Django 5.0.4 on 2024-05-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverAndglass', '0003_remove_coverandglassproduct_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverandglassproduct',
            old_name='color',
            new_name='Cover_Color',
        ),
    ]
