# Generated by Django 5.0.4 on 2024-05-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverAndglass', '0004_rename_color_coverandglassproduct_cover_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Cover_Color',
        ),
    ]
