# Generated by Django 5.0.4 on 2024-04-30 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneAndtablet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonespecification',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phoneAndtablet.phonecategory'),
        ),
    ]
