# Generated by Django 5.0.4 on 2024-04-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneAndtablet', '0002_phonespecification_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonetabletproduct',
            name='color',
        ),
        migrations.AddField(
            model_name='phonetabletproduct',
            name='color',
            field=models.ManyToManyField(related_name='products', to='phoneAndtablet.phonecolor'),
        ),
    ]
