# Generated by Django 5.0.4 on 2024-05-01 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneAndtablet', '0003_remove_phonetabletproduct_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductStorage',
            new_name='PhoneNetwork',
        ),
        migrations.AddField(
            model_name='phonetabletproduct',
            name='phone_network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='phoneAndtablet.phonenetwork'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonetabletproduct',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='phoneAndtablet.phonesim'),
        ),
        migrations.AddField(
            model_name='phonetabletproduct',
            name='phone_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='phoneAndtablet.phonetype'),
            preserve_default=False,
        ),
    ]
