# Generated by Django 5.0.4 on 2024-05-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneAndtablet', '0004_phonesim_phonestorage_phonetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phoneAndtablet/media/image'),
        ),
    ]
