# Generated by Django 5.0.4 on 2024-05-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraproduct',
            name='image',
            field=models.ImageField(upload_to='cemera/media/image'),
        ),
    ]
