# Generated by Django 5.0.4 on 2024-04-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='smartWatchCategroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='smartWatch/media/image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='smartWatchSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchStrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='smartWatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchSpecificaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=350)),
                ('DisplaySize', models.CharField(max_length=350)),
                ('Compatiblewith', models.CharField(max_length=350)),
                ('OtherFeaturesInfo', models.CharField(max_length=350)),
                ('ChargingInterface', models.CharField(max_length=350)),
                ('CallingFeatures', models.CharField(max_length=350)),
                ('Batterycapacity', models.CharField(max_length=350)),
                ('Material', models.CharField(max_length=350)),
                ('Chargingtime', models.CharField(max_length=350)),
                ('OS', models.CharField(max_length=350)),
                ('Display', models.CharField(max_length=350)),
                ('SweatWaterResistance', models.CharField(max_length=350)),
                ('Chipset', models.CharField(max_length=350)),
                ('Memory', models.CharField(max_length=350)),
                ('BatteryLife', models.CharField(max_length=350)),
                ('OtherFeaturesnfo', models.CharField(max_length=350)),
                ('categroy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartWatch.smartwatchcategroy')),
            ],
        ),
        migrations.CreateModel(
            name='PowerTabletProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('status', models.CharField(choices=[('In Stock ', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=40)),
                ('image', models.ImageField(upload_to='smartWatch/media/image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('color', models.ManyToManyField(related_name='products', to='smartWatch.color')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartWatch.smartwatchcategroy')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartWatch.smartwatchdescription')),
                ('SmartWatchEdition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartWatch.smartwatchedition')),
                ('SmartWatchNetwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartWatch.smartwatchnetwork')),
                ('smartWatchSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartWatch.smartwatchsize')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartWatch.smartwatchspecificaion')),
                ('SmartWatchStrap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartWatch.smartwatchstrap')),
                ('smartWatchType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartWatch.smartwatchtype')),
                ('SmartWatchWarranty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartWatch.smartwatchwarranty')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
