# Generated by Django 5.0.4 on 2024-04-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartWatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PowerTabletProduct',
            new_name='smartWatchProduct',
        ),
    ]
