# Generated by Django 5.0.4 on 2024-04-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartWatch', '0002_rename_powertabletproduct_smartwatchproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartwatchspecificaion',
            name='ChargingInterface',
        ),
    ]
