# Generated by Django 5.0.4 on 2024-04-30 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phone_and_tablet/media/image')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
            },
        ),
        migrations.CreateModel(
            name='LaptobRim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LaptobStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LaptobWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LaptopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=350)),
                ('keyboard_type', models.CharField(max_length=350)),
                ('storage_capacity', models.CharField(max_length=350)),
                ('storage_type', models.CharField(max_length=350)),
                ('graphics_model', models.CharField(max_length=350)),
                ('model', models.CharField(max_length=350)),
                ('graphics', models.CharField(max_length=350)),
                ('interface_port', models.CharField(max_length=350)),
                ('weight', models.CharField(max_length=350)),
                ('display_type', models.CharField(blank=True, max_length=350, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=350, null=True)),
                ('display_size', models.CharField(max_length=350)),
                ('adapter_type', models.CharField(max_length=350)),
                ('os', models.CharField(max_length=350)),
                ('chipset', models.CharField(max_length=350)),
                ('memory', models.CharField(max_length=350)),
                ('audio', models.CharField(max_length=350)),
                ('battery_info', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
            },
        ),
        migrations.CreateModel(
            name='laptobAnddesktopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock ', 'Out Of Stock ')], max_length=40)),
                ('keyboard', models.CharField(choices=[('Arabic', 'Arabic'), ('Regular', 'Regular')], max_length=40)),
                ('image', models.ImageField(upload_to='laptobAnddesktop/media/image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loptobAnddesktop.laptobdescription')),
                ('Ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loptobAnddesktop.laptobrim')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loptobAnddesktop.laptobstorage')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loptobAnddesktop.laptobwarranty')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loptobAnddesktop.laptopcategory')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loptobAnddesktop.laptopspecification')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
