# Generated by Django 5.0.4 on 2024-04-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptobAnddesktop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptobanddesktopproduct',
            name='image',
            field=models.ImageField(upload_to='loptobAnddesktop/media/image'),
        ),
        migrations.AlterField(
            model_name='laptobdescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='loptobAnddesktop/media/image'),
        ),
    ]
